interface ICoinConstants
{
    GET_ASSETS_REQUEST: string,
    GET_ASSETS_SUCCESS: string,
    GET_ASSETS_ERROR: string,

    GET_CURRENT_EXCHANGERATE_REQUEST: string
    GET_CURRENT_EXCHANGERATE_SUCCESS: string,
    GET_CURRENT_EXCHANGERATE_ERROR: string,

    GET_TIME_PERIODS_REQUEST: string,
    GET_TIME_PERIODS_SUCCESS: string,
    GET_TIME_PERIODS_ERROR: string
}

export const coinConstants: ICoinConstants =
{
    GET_ASSETS_REQUEST: "GET_ASSETS_REQUEST",
    GET_ASSETS_SUCCESS: "GET_ASSETS_SUCCESS",
    GET_ASSETS_ERROR: "GET_ASSETS_ERROR",

    GET_CURRENT_EXCHANGERATE_REQUEST: "GET_CURRENT_EXCHANGERATE_REQUEST",
    GET_CURRENT_EXCHANGERATE_SUCCESS: "GET_CURRENT_EXCHANGERATE_SUCCESS",
    GET_CURRENT_EXCHANGERATE_ERROR: "GET_CURRENT_EXCHANGERATE_ERROR",

    GET_TIME_PERIODS_REQUEST: "GET_TIME_PERIODS_REQUEST",
    GET_TIME_PERIODS_SUCCESS: "GET_TIME_PERIODS_SUCCESS",
    GET_TIME_PERIODS_ERROR: "GET_TIME_PERIODS_ERROR"
}